name: Build and Push to Artifact Registry
on:
  push:
    branches: [main]

env:
  GCP_PROJECT: isn-2025-2
  AR_LOCATION: southamerica-east1
  AR_REPO: basic-movie-recommender
  IMAGE_NAME: basic-movie-recommender

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Google Cloud auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: |
          echo "Logging docker to Artifact Registry"
          gcloud --quiet auth configure-docker ${AR_LOCATION}-docker.pkg.dev

      - name: Build Docker image
        run: |
          IMAGE=${AR_LOCATION}-docker.pkg.dev/${GCP_PROJECT}/${AR_REPO}/${IMAGE_NAME}:$GITHUB_SHA
          docker build -t $IMAGE .

      - name: Push to Artifact Registry
        run: |
          IMAGE=${AR_LOCATION}-docker.pkg.dev/${GCP_PROJECT}/${AR_REPO}/${IMAGE_NAME}:$GITHUB_SHA
          docker push $IMAGE

      - name: Output image
        run: |
          echo "Pushed image: ${AR_LOCATION}-docker.pkg.dev/${GCP_PROJECT}/${AR_REPO}/${IMAGE_NAME}:$GITHUB_SHA"
